### ISSUE TITLE
How to Remove Disk ?

### ISSUE THREAD

**Issue by sleepingpandaxx** [ParveenBhadooOfficial/Bhadoo-Cloud#28]
After my vps disk full 99% how to remove it ?

**Comment by ParveenBhadooOfficial** [comment]
You can also Delete the Container using below if needed.
  sudo docker stop $(docker ps -a -q)
  sudo docker rm $(docker ps -a -q)
You can also remove pulled image to pull latest image again.
  sudo docker images -a
  
  sudo docker rmi Image Image2
